version: "3.8"

services:
  # PostgreSQL for outbox pattern storage
  postgres:
    image: postgres:16-alpine
    container_name: outbox-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: outbox_db
      POSTGRES_USER: outbox_user
      POSTGRES_PASSWORD: outbox_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  # Zookeeper for Kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: outbox-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    restart: unless-stopped

  # Kafka broker
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: outbox-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_HOST://kafka:9094
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_HOST
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_NUM_PARTITIONS: 6
    restart: unless-stopped

  # Kafka UI for monitoring
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: outbox-kafka-ui
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9094
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    restart: unless-stopped
  # pgAdmin for PostgreSQL monitoring
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: outbox-pgadmin
    depends_on:
      - postgres
    ports:
      - "8082:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: unless-stopped

  # Producer Services (3 instances)
  producer1:
    build:
      context: ./ProducerService
      dockerfile: Dockerfile
    container_name: outbox-producer1
    depends_on:
      - postgres
      - kafka
    ports:
      - "5301:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - SERVICE_ID=producer-1
      - INSTANCE_ID=producer-1-instance
      - ASPNETCORE_HTTP_PORTS=80
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=outbox_db;Username=outbox_user;Password=outbox_password
      - ConnectionStrings__Kafka=kafka:9094
    restart: unless-stopped
    networks:
      - default

  producer2:
    build:
      context: ./ProducerService
      dockerfile: Dockerfile
    container_name: outbox-producer2
    depends_on:
      - postgres
      - kafka
    ports:
      - "5302:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - SERVICE_ID=producer-2
      - INSTANCE_ID=producer-2-instance
      - ASPNETCORE_HTTP_PORTS=80
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=outbox_db;Username=outbox_user;Password=outbox_password
      - ConnectionStrings__Kafka=kafka:9094
    restart: unless-stopped
    networks:
      - default

  producer3:
    build:
      context: ./ProducerService
      dockerfile: Dockerfile
    container_name: outbox-producer3
    depends_on:
      - postgres
      - kafka
    ports:
      - "5303:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - SERVICE_ID=producer-3
      - INSTANCE_ID=producer-3-instance
      - ASPNETCORE_HTTP_PORTS=80
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=outbox_db;Username=outbox_user;Password=outbox_password
      - ConnectionStrings__Kafka=kafka:9094
    restart: unless-stopped
    networks:
      - default

  # Consumer Services Group A (3 instances)
  consumer1:
    build:
      context: ./ConsumerService
      dockerfile: Dockerfile
    container_name: outbox-consumer1
    depends_on:
      - postgres
      - kafka
    ports:
      - "5401:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - SERVICE_ID=consumer-1
      - INSTANCE_ID=consumer-1-instance
      - KAFKA_CONSUMER_GROUP=group-a
      - KAFKA_TOPICS=shared-events
      - ASPNETCORE_HTTP_PORTS=80
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=outbox_db;Username=outbox_user;Password=outbox_password
      - ConnectionStrings__Kafka=kafka:9094
      - ProducerService__BaseUrl=http://producer1
    restart: unless-stopped
    networks:
      - default

  consumer2:
    build:
      context: ./ConsumerService
      dockerfile: Dockerfile
    container_name: outbox-consumer2
    depends_on:
      - postgres
      - kafka
    ports:
      - "5402:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - SERVICE_ID=consumer-2
      - INSTANCE_ID=consumer-2-instance
      - KAFKA_CONSUMER_GROUP=group-a
      - KAFKA_TOPICS=shared-events
      - ASPNETCORE_HTTP_PORTS=80
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=outbox_db;Username=outbox_user;Password=outbox_password
      - ConnectionStrings__Kafka=kafka:9094
      - ProducerService__BaseUrl=http://producer1
    restart: unless-stopped
    networks:
      - default

  consumer3:
    build:
      context: ./ConsumerService
      dockerfile: Dockerfile
    container_name: outbox-consumer3
    depends_on:
      - postgres
      - kafka
    ports:
      - "5403:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - SERVICE_ID=consumer-3
      - INSTANCE_ID=consumer-3-instance
      - KAFKA_CONSUMER_GROUP=group-a
      - KAFKA_TOPICS=shared-events
      - ASPNETCORE_HTTP_PORTS=80
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=outbox_db;Username=outbox_user;Password=outbox_password
      - ConnectionStrings__Kafka=kafka:9094
      - ProducerService__BaseUrl=http://producer1
    restart: unless-stopped
    networks:
      - default

  # Consumer Services Group B (2 instances)
  consumer4:
    build:
      context: ./ConsumerService
      dockerfile: Dockerfile
    container_name: outbox-consumer4
    depends_on:
      - postgres
      - kafka
    ports:
      - "5404:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - SERVICE_ID=consumer-4
      - INSTANCE_ID=consumer-4-instance
      - KAFKA_CONSUMER_GROUP=group-b
      - KAFKA_TOPICS=shared-events
      - ASPNETCORE_HTTP_PORTS=80
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=outbox_db;Username=outbox_user;Password=outbox_password
      - ConnectionStrings__Kafka=kafka:9094
      - ProducerService__BaseUrl=http://producer1
    restart: unless-stopped
    networks:
      - default

  consumer5:
    build:
      context: ./ConsumerService
      dockerfile: Dockerfile
    container_name: outbox-consumer5
    depends_on:
      - postgres
      - kafka
    ports:
      - "5405:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - SERVICE_ID=consumer-5
      - INSTANCE_ID=consumer-5-instance
      - KAFKA_CONSUMER_GROUP=group-b
      - KAFKA_TOPICS=shared-events
      - ASPNETCORE_HTTP_PORTS=80
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=outbox_db;Username=outbox_user;Password=outbox_password
      - ConnectionStrings__Kafka=kafka:9094
      - ProducerService__BaseUrl=http://producer1
    restart: unless-stopped
    networks:
      - default

  # Consumer Services Group C (1 instance)
  consumer6:
    build:
      context: ./ConsumerService
      dockerfile: Dockerfile
    container_name: outbox-consumer6
    depends_on:
      - postgres
      - kafka
    ports:
      - "5406:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - SERVICE_ID=consumer-6
      - INSTANCE_ID=consumer-6-instance
      - KAFKA_CONSUMER_GROUP=group-c
      - KAFKA_TOPICS=shared-events
      - ASPNETCORE_HTTP_PORTS=80
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=outbox_db;Username=outbox_user;Password=outbox_password
      - ConnectionStrings__Kafka=kafka:9094
      - ProducerService__BaseUrl=http://producer1
    restart: unless-stopped
    networks:
      - default

volumes:
  postgres_data:
    driver: local

networks:
  default:
    name: outbox-network
